name: turmoric
channels:
  - conda-forge
dependencies: 
  - numpy
  - pandas>=2.2.3
  - scikit-learn>=1.6.1 
  - scikit-image>=0.25.0
  - matplotlib>=3.10.1
  - pip>=23.1.2
  - scipy>=1.11.1
  - seaborn>=0.12.2
  - setuptools>=65.5.0
  - tifffile>=2025.3.13
  - pip:
    - opencv-python>=4.11
